//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListInfo
    {
        public long Id { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string EMSCode { get; set; }
        public string Order { get; set; }
        public string DocumentType { get; set; }
        public string FullName { get; set; }
        public string HowToReadName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string BasicPensionNumber { get; set; }
        public string PlaceOfBirth { get; set; }
        public string USDBankNumber { get; set; }
        public string VNDBankNumber { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string EmployeeManager { get; set; }
        public string TicketWindow { get; set; }
        public string Error { get; set; }
        public string Reason { get; set; }
        public double AdvanceFee { get; set; }
        public double ErrorFee { get; set; }
        public double OtherFee { get; set; }
        public double Cost { get; set; }
        public double AverageWage { get; set; }
        public double Coefficient { get; set; }
        public double Pension { get; set; }
        public double FirstTime { get; set; }
        public string MonthOfFirstTime { get; set; }
        public double SecondTime { get; set; }
        public string MonthOfSecondTime { get; set; }
        public double CostOfLiving { get; set; }
        public double Calculate { get; set; }
        public string Pay { get; set; }
        public Nullable<System.DateTime> DateToPay { get; set; }
        public double Deduct { get; set; }
        public double AverageWage_Tax { get; set; }
        public double Coefficient_Tax { get; set; }
        public double Pension_Tax { get; set; }
        public double FirstTime_Tax { get; set; }
        public double SecondTime_Tax { get; set; }
        public Nullable<int> IdList { get; set; }
        public bool IsError { get; set; }
        public bool FInUse { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    }
}
